apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: uicesmeda-nodejs 
  janus-idp.io/tekton: uicesmeda-nodejs
  backstage.io/kubernetes-id: uicesmeda-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: uicesmeda-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  